#!/usr/bin/env python


import sys
from mathematics import avg


# Usage: _avg <value1 ... valuen> 
if len(sys.argv) > 1:
    print avg([float(x) for x in sys.argv[1:]])

# Usage: <value1 ... valuen> | _avg 
else:
    print avg([float(x) for x in sys.stdin])

    
