#!/usr/bin/env python

import sys
from mathematics import div


# Usage: <value1 ... valuen> | _div a 
if len(sys.argv) == 2:
    print div([float(x) for x in sys.stdin], float(sys.argv[1]))

# Usage: _div a <value1 ... valuen>
elif len(sys.argv) > 1:
    print div([float(x) for x in sys.argv[2:]], float(sys.argv[1]))

else:
    msg = "Invalid input."
    raise ValueError(msg)
