#!/usr/bin/env python

import sys


# Usage: max <value1 ... valuen> 
if len(sys.argv) > 1:
    print max([float(x) for x in sys.argv[1:]])

# Usage: <value1 ... valuen> | max 
else:
    print max([float(x) for x in sys.stdin])

    
