#!/usr/bin/env python

import sys


# Usage: _min <value1 ... valuen> 
if len(sys.argv) > 1:
    print min([float(x) for x in sys.argv[1:]])

# Usage: <value1 ... valuen> | _min 
else:
    print min([float(x) for x in sys.stdin])

    
