#!/usr/bin/env python

import sys
from mathematics import mult


# Usage: <value1 ... valuen> | _mult a 
if len(sys.argv) == 2:
    print mult(float(sys.argv[1]), [float(x) for x in sys.stdin])

# Usage: _mult a <value1 ... valuen> 
elif len(sys.argv) > 1 and len(sys.argv) != 2:
    print mult(float(sys.argv[1]), [float(x) for x in sys.argv[2:]])

else:
    msg = "Invalid input."
    raise ValueError(msg)
