#!/usr/bin/env python

import sys
from mathematics import std


# Usage: _std <value1 ... valuen> 
if len(sys.argv) > 1:
    print std([float(x) for x in sys.argv[1:]])

# Usage: <value1 ... valuen> | _std 
else:
    print std([float(x) for x in sys.stdin])


