#!/usr/bin/env python

import sys


# Usage: avg <value1 ... valuen> 
if len(sys.argv) > 1:
    print sum([float(x) for x in sys.argv[1:]])

# Usage: <value1 ... valuen> | avg 
else:
    print sum([float(x) for x in sys.stdin])

    
